// Auto-generated by Neutron. Do not edit.
declare module "@neutron-build/core" {
  interface NeutronGeneratedRouteMap {
    paths:
    | "/"
    | "/console"
    | `/entity/${string}`
    | "/login"
    | "/objective"
    | "/scanner"
    | "/search"
    | "/setup"
    | "/system"
  }
}

export {};
