// Auto-generated by Neutron. Do not edit.
declare module "@neutron-build/core" {
  interface NeutronGeneratedRouteMap {
    paths:
    | "/"
    | "/briefing"
    | `/entity/${string}`
    | "/objective"
  }
}

export {};
